services:
    scalolaz.phpbb3scrollBtn.listener:
        class: scalolaz\phpbb3scrollBtn\event\listener
        arguments:
        - @template
        - @user
        - @dbal.conn
        - %core.root_path%
        - %core.php_ext%
        tags:
            - { name: event.listener }